/net/fantasia/home/atks/dev/vt/pipeline/generate_gatk_haplotypecaller_pipeline_makefile.pl \
-o /net/fantasia/home/atks/dev/vt/comparisons/na12878/hc \
-b /net/fantasia/home/atks/dev/vt/comparisons/programs/vt \
-t /net/fantasia/home/atks/programs/cluster \
-m hc.mk \
-c mini+ \
-d 80 \
-s na12878.high_coverage.index \
-l chr20.hs37d5.seq.length.txt \
-i 1000000 \
-r /net/1000g/atks/ref/genome/hs37d5.fa \
-j 4g \