/net/fantasia/home/atks/dev/vt/pipeline/generate_gatk_unifiedgenotyper_calling_pipeline_makefile.pl \
-o /net/fantasia/home/atks/dev/vt/comparisons/na12878/ug \
-b /net/fantasia/home/atks/dev/vt/comparisons/programs/vt \
-t /net/fantasia/home/atks/programs/cluster \
-m ug.mk \
-c mini \
-d 5 \
-s na12878.high_coverage.index \
-l hs37d5.seq.length.txt \
-i 1000000 \
-r /net/bipolar/atks/ref/hs37d5.fa \
-j 4g \
-v BOTH